// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.


//$(function(){
//    $(document).click(function (e) {
//      lxid = $(e.target).attr('id');  // 获取id
//	  	conlog(lxid);
//    })
//})
var lxid = "LX0";
function LXid(obj){
	
	lxid = obj.id;
	chartresize2();//温度
	chartresize();//湿度
	chartresize1();//氨气，灵嗅一号
	chartresize3();//硫化氢，灵嗅二号
	chartresize4();//甲苯，灵嗅三号
	chartresize5();//品质
}



function conlog(event){
	console.log(event);  //不是所有浏览器都支持console ,遇到不支持就直接注销此方法
}


//$(document).on('click',function(e){
//console.log(e.toElement.value);//获取点击元素的value值
//console.log(e.toElement.innerHTML);//获取点击的元素的html内容
//})


//显示隐藏 暂停使用
//$(document).ready(function(){
//	$(".clickA").on("click",chartA);
//});
//function chartA(){
//	$("#chart").removeClass("chartdisplay");
//}




//$(document).ready(function(){
//	$(".lishi").on("click",chartresize2);
//});

//下面是三个图表
// 基于准备好的dom，初始化echarts实例
//        var myChart = echarts.init(document.getElementById('temChart'));
//
//        // 指定图表的配置项和数据
//        var option = {
//            title: {
//                text: ''
//            },
//            tooltip: {},
//            legend: {
//                data:['温度℃']
//            },
//            xAxis: {
//                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
//            },
//            yAxis: {},
//            series: [{
//                name: '温度℃',
//                type: 'line',
//                data: [3, 3.66, 3, 3.5, 3.57, 3.35]//Y轴数据，温度
//            }]
//        };
//
//        // 使用刚指定的配置项和数据显示图表。
//        myChart.setOption(option);
    

                            // 温度
function chartresize2(){
	         $("#chart").addClass("chartdisplay") 
             console.log("chartresize2");
             var temp2 = new initchart2();
             temp2.resize();
         }
	var initchart2 = function(){
		 var chart1 = echarts.init(document.getElementById('temChart'));
     if(lxid=="LX1"){
		var chart1_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['温度℃']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15.40","15.50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '温度℃',
                type: 'line',
                data: [2, 4, 6, 3,1,5]//Y轴数据，一号车温度
            }]
    }
		}else if(lxid=="LX2"){
			var chart1_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['温度℃']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15.40","15.50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '温度℃',
                type: 'line',
                data: [1, 4, 6, 6,6,3]//Y轴数据，二号车温度
            }]
    }
		}else if(lxid=="LX3"){
				var chart1_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['温度℃']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15.40","15.50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '温度℃',
                type: 'line',
                data: [1, 4, 6, 3,6,3]//Y轴数据，三号车温度
            }]
    }
		}else if(lxid=="LX0"){
				var chart1_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['温度℃']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15.40","15.50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '温度℃',
                type: 'line',
                data: [2, 4, 6, 3,1,5]//Y轴数据，一号车温度
            }]
    }
		}
    chart1.setOption(chart1_option);
    $(function(){
        window.onresize = function(){
            chart1.resize();
        }
    })
    this.resize = function size(){
        var chart1div=document.getElementById('temChart');
        var tabcontent2 = document.getElementById('TabContent1');
        width=tabcontent2.offsetWidth;
        height=tabcontent2.offsetHeight;
        chart1div.style.width=width+'px';
        chart1div.style.height=height+'px';
        chart1.resize(width,height);
    }
}
	



                                                 //湿度
function chartresize(){
             console.log("chartresize");
	         
             var temp = new initchart();
             temp.resize();
         }
var initchart = function(){
   var chart2 = echarts.init(document.getElementById('humichart'));
if(lxid=="LX1"){   //一号车
	var chart2_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['湿度%RH']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '湿度%RH',
                type: 'line',
                data: [8.65, 5, 6, 9,9.1,8.1]//Y轴数据，一号车湿度
            }]
    }
	}else if(lxid=="LX2"){   //二号车
	  var chart2_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['湿度%RH']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '湿度%RH',
                type: 'line',
                data: [1, 2, 6, 9,8,1]//Y轴数据，二号车湿度
            }]
    }	
	}else if(lxid=="LX3"){
	   var chart2_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['湿度%RH']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '湿度%RH',
                type: 'line',
                data: [5, 2, 3, 9,4,9]//Y轴数据，三号车湿度
            }]
    }	
	   }else if(lxid=="LX0"){ //刚进入页面什么都没点的情况 填一号车的数据
		   var chart2_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['湿度%RH']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '湿度%RH',
                type: 'line',
                data: [5, 2, 3, 9,4,9]//Y轴数据，一号车湿度
            }]
    }
	   }
    chart2.setOption(chart2_option);
    $(function(){
        window.onresize = function(){
            chart2.resize();
        }
    })
    this.resize = function size(){
        var chart2div=document.getElementById('humichart');
        var tabcontent = document.getElementById('TabContent1');
        width=tabcontent.offsetWidth;
        height=tabcontent.offsetHeight;
        chart2div.style.width=width+'px';
        chart2div.style.height=height+'px';
        chart2.resize(width,height);
    }
}
		 
                                                    //	氨气	 
function chartresize1(){
             console.log("chartresize1");
             var temp1 = new initchart1();
             temp1.resize();
         }
	     var initchart1 = function(){
    var chart3 = echarts.init(document.getElementById('gchart'));
    if(lxid=="LX1"){            //一号车
	var chart3_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['氨气']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '氨气',
                type: 'line',
                data: [1, 5, 6, 2,7.56,8.55]//Y轴数据，一号车氨气含量
            }]
    }}else if(lxid=="LX2"){   //二号车
		var chart3_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['氨气']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '氨气',
                type: 'line',
                data: [10, 5, 6, 2,7.56,8.55]//Y轴数据，二号车氨气含量
            }]
    }
	}else if(lxid=="LX3"){    //三号车
		var chart3_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['氨气']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '氨气',
                type: 'line',
                data: [1, 5, 6, 9,7.56,8.55]//Y轴数据，三号车氨气含量
            }]
    }
	}else if(lxid=="LX0"){              //刚进入页面什么都没点的情况 填一号车的数据
		var chart3_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['氨气']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '氨气',
                type: 'line',
                data: [1, 5, 6, 9,7.56,3]//Y轴数据，一号车氨气含量
            }]
    }
	}
    chart3.setOption(chart3_option);
    $(function(){
        window.onresize = function(){
            chart3.resize();
        }
    })
    this.resize = function size(){
        var chart3div=document.getElementById('gchart');
        var tabcontent1 = document.getElementById('TabContent1');
        width=tabcontent1.offsetWidth;
        height=tabcontent1.offsetHeight;
        chart3div.style.width=width+'px';
        chart3div.style.height=height+'px';
        chart3.resize(width,height);
    }
}
	
	
	                                                       //硫化氢
function chartresize3(){
             console.log("chartresize3");
             var temp3 = new initchart3();
             temp3.resize();
         }
	     var initchart3 = function(){
    var chart4 = echarts.init(document.getElementById('HSchart'));
    if(lxid=="LX1"){    //一号车
	var chart4_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['硫化氢']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '硫化氢',
                type: 'line',
                data: [3, 5, 3, 3,4.11,4.45]//Y轴数据，一号车硫化氢含量
            }]
    }}else if(lxid=="LX2"){      //二号车
		var chart4_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['硫化氢']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '硫化氢',
                type: 'line',
                data: [3, 5, 5, 3,4.11,5.45]//Y轴数据，二号车硫化氢含量
            }]
    }
	}else if(lxid=="LX3"){      //三号车
		var chart4_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['硫化氢']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '硫化氢',
                type: 'line',
                data: [3, 1, 5, 3,4.11,1.45]//Y轴数据，三号车硫化氢含量
            }]
    } 
	}else if(lxid=="LX0"){                     //刚进入页面什么都没点的情况 填一号车的数据
		var chart4_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['硫化氢']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '硫化氢',
                type: 'line',
                data: [3, 1, 5, 3,4.11,1.45]//Y轴数据，一号车硫化氢含量
            }]
    }
	}
		
    chart4.setOption(chart4_option);
    $(function(){
        window.onresize = function(){
            chart4.resize();
        }
    })
    this.resize = function size(){
        var chart4div=document.getElementById('HSchart');
        var tabcontent4 = document.getElementById('TabContent1');
        width=tabcontent4.offsetWidth;
        height=tabcontent4.offsetHeight;
        chart4div.style.width=width+'px';
        chart4div.style.height=height+'px';
        chart4.resize(width,height);
    }
}
	
                                                    //甲苯	
function chartresize4(){
             console.log("chartresize4");
             var temp4 = new initchart4();
             temp4.resize();
         }
	     var initchart4 = function(){
    var chart5 = echarts.init(document.getElementById('JBchart'));
	if(lxid=="LX1"){
		var chart5_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['甲苯']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '甲苯',
                type: 'line',
                data: [7, 6, 6, 6.55,8.55,8.12]//Y轴数据，一号车甲苯含量
            }]
    }
	}		 
	else if(lxid=="LX2"){   //二号车
		var chart5_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['甲苯']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '甲苯',
                type: 'line',
                data: [3, 6, 6, 6.55,3.55,8.12]//Y轴数据，二号车甲苯含量
            }]
    }
	}else if(lxid=="LX3"){   //三号车
		var chart5_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['甲苯']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '甲苯',
                type: 'line',
                data: [7, 6, 6, 6.55,3.55,8.12]//Y轴数据，三号车甲苯含量
            }]
    }
	}else if(lxid=="LX0"){              //一号车
		var chart5_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['甲苯']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '甲苯',
                type: 'line',
                data: [7, 6, 6, 6.55,8.55,8.12]//Y轴数据，一号车甲苯含量
            }]
    }
	}
    chart5.setOption(chart5_option);
    $(function(){
        window.onresize = function(){
            chart5.resize();
        }
    })
    this.resize = function size(){
        var chart5div=document.getElementById('JBchart');
        var tabcontent5 = document.getElementById('TabContent1');
        width=tabcontent5.offsetWidth;
        height=tabcontent5.offsetHeight;
        chart5div.style.width=width+'px';
        chart5div.style.height=height+'px';
        chart5.resize(width,height);
    }
}
		
                                                  //品质	
function chartresize5(){
             console.log("chartresize5");
             var temp5 = new initchart5();
             temp5.resize();
         }
	     var initchart5 = function(){
    var chart6 = echarts.init(document.getElementById('Pinzhi'));
    if(lxid=="LX1"){
		var chart6_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['品质']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '品质',
                type: 'line',
                data: [1, 2, 3, 4,4,3]//Y轴数据，一号车品质
            }]
    }
	} 
	else if(lxid=="LX2"){   //二号车
		var chart6_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['品质']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '品质',
                type: 'line',
                data: [1, 4, 3, 4,4,3]//Y轴数据，二号车品质
            }]
    }
	}else if(lxid=="LX3"){  //三号车
		var chart6_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['品质']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '品质',
                type: 'line',
                data: [3, 2, 3, 3,4,3]//Y轴数据，三号车品质
            }]
    }
	}else if(lxid=="LX0"){  //一号车
		var chart6_option={
        title: {
                text: ''
            },
            tooltip: {},
            legend: {
                data:['品质']
            },
            xAxis: {
                data: ["15：00","15：10","15：20","15：30","15：40","15：50"]//X轴数据，时间
            },
            yAxis: {},
            series: [{
                name: '品质',
                type: 'line',
                data: [1, 2, 3, 4,4,3]//Y轴数据，一号车品质
            }]
    }
	}
    chart6.setOption(chart6_option);
    $(function(){
        window.onresize = function(){
            chart6.resize();
        }
    })
    this.resize = function size(){
        var chart6div=document.getElementById('Pinzhi');
        var tabcontent6 = document.getElementById('TabContent1');
        width=tabcontent6.offsetWidth;
        height=tabcontent6.offsetHeight;
        chart6div.style.width=width+'px';
        chart6div.style.height=height+'px';
        chart6.resize(width,height);
    }
}
	
		 
		 
//跟随导航
$(function(){
var nav=$("#headerNav"); //得到导航对象
var win=$(window); //得到窗口对象
var sc=$(document);//得到document文档对象。
win.scroll(function(){
  if(sc.scrollTop()>=350){    //数字为下拉多少px触发特效
    nav.addClass("fixednav"); 
   $(".navTmp").fadeIn(); 
  }else{
   nav.removeClass("fixednav");
   $(".navTmp").fadeOut();
  }
})  
})	

	
	
	
	
	
	
	
	
	
	
	
	
	